num=set()
num1=int(input("Enter the number:"))
num.add(num1)
num2=int(input("Enter the number:"))
num.add(num2)
num3=int(input("Enter the number:"))
num.add(num3)
num4=int(input("Enter the number:"))
num.add(num4)
num5=int(input("Enter the number:"))
num.add(num5)
num6=int(input("Enter the number:"))
num.add(num6)
num7=int(input("Enter the number:"))
num.add(num7)
num8=int(input("Enter the number:"))
num.add(num8)
print(num,type(num))